# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf1c4a070193b5dbb2f74552e422c99b96118ef6ac9afae32aa1157fa6ab285c63e8a3987a804814132bb0d355081232f7d39815431f76919faf54e11158f687

test:
  secret_key_base: 34ef8d660718797a81772d0a247fd9a93644c256129e7dcfc1f2c2149d18eee88fefd72f3a197f615d1b338073a077f7488c0a62f72375b27a49ab7265c63b46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
